### PR TITLE
style(home): ReImagine Cards layout

### PR DESCRIPTION
**Pull request by Volley-Freak**
Responsive card design updated for screen width >900

 
Screenshot at Oct 08 15-20-59

Fixes : #102

### CODE REVIEW

**Comment by ashuvssut** [comment]
Kindly go through contributing.md that show how to properly setup you devlopment enviornment.

1. You are using npm. we are using yarn. You have upgraded some packages. This was unnecessary.(follow the dev env setup steps)
2. There are unnecessary/irrelevant files committed in this PR. Only ReImagineCommite tsx file was needed.
3. Always Link PR to its respective (Kindly please read contributing.md before creating PRs/ Issue. Everything is mentioned there.)

**Comment by Volley-Freak** [comment]
Sorry for the inconveniences. You can merge the RelmagineCommite.tsx only or should I make another pull request?

**Comment by ashuvssut** [comment]
You can push more commits to your `card-design` to update this PR. create commits that does all the mentioned corrections

**Comment by Volley-Freak** [comment]
I've made the changes please go through it and let me know it it's fine

**Comment by ashuvssut** [comment]
> 3. Always Link PR to its respective (Kindly please read contributing.md before creating PRs/ Issue. Everything is mentioned there.)

**Please read contributing.md.**

**Comment by Volley-Freak** [comment]
> Each row now has two items at width > 900px. 
This resolves issue: [#107](https://github.com/WalkingPal/walking-pal-web/pull/107)

**Comment by Volley-Freak** [comment]
Responsive design for ReImagine commute card is updated specially for width > 900px.

Fixes : [#102 ](https://github.com/WalkingPal/walking-pal-web/issues/102)

**Comment by ashuvssut** [comment]
I have updated your PR description. see there

**Pull request merged**
