### PR TITLE
fix: Reject strings with spaces for first and last name on register page

### LINKED ISSUE #156: bug: Wrong validation while registering
### Description

At the moment, users can register with empty first and last names.

### Steps
- Go to [registration page](https://walkingpal.in/register)
- Add 2 or more empty spaces
- Click Next
- See bug

### What I want
- Users shouldn't be able to register with empty spaces

### PR DESCRIPTION
**Pull request by batflarrow**
## Proposed Changes

- fixes #156
Trimming the string before the validation so that spaces are removed and hence strings with empty spaces will no longer be accepted for first and last name.

Preview

https://user-images.githubusercontent.com/56157504/197939527-87348bc4-4ebb-4e8b-bd4d-8aca190951a2.mp4

### CODE REVIEW

**Comment by ashuvssut** [comment]
Hi! batflarrow. 

checkout pages/api

we do server side validation using `zod`

Do these same changes for `zod` validations too. (`z.string().trim()...`)

**Comment by batflarrow** [comment]
> Hi! @batflarrow
> 
> checkout pages/api. we do server side validation using `zod`
> 
> Do these same changes for `zod` validations too. (`z.string().trim()...`)

Made this change, Also made a similar change for name validation in https://github.com/batflarrow/walking-pal-web/blob/06da9262a14581fe1fd54cbf1bf147244ccded79/components/FeedbackForm/components/formValidation.ts#L19

**Comment by ashuvssut** [comment]
@batflarrow, I would say, do a global search with keyword `.string()`. You will find zod and yup validations where trim() is required.

We need to trim all those strings which have a `.min(n)` validation chaining (eg `firstname`, `lastname`, `message`, etc)

**Comment by batflarrow** [comment]
> @batflarrow, I would say, do a global search with keyword `.string()` across the codebase. You will find many zod and yup validations where trim() is required.
> 
> We need to trim all those strings which have a `.min(n)` validation chaining (eg `firstname`, `lastname`, `message`, etc)

Yeah Makes sense, done.

**Comment by ashuvssut** [comment]
Nicely done! thanks

**Pull request merged**
