### PR TITLE
feat: founders-hub svg

### LINKED ISSUE #141: feat(UI/UX Design): convert simple PNG images to SVGs
### Description

There are some PNGs in the webisite like these:
image

Create PRs to convert each of these simple PNGs to SVGs (PNGs can not be convert to SVGs. You need to use tools like Adobe Illustrator, figma, etc to design these vector graphics. refer PR #32 for reference --- this PR converted the logo PNG to SVG.)

Create 1 PR for 1 PNG conversion. Multiple contributors can be assigned to this issue. 

⚠**Contributors who are interested, please tell beforehand that which PNG you are going to start working on. This will avoid clashes (possibility of 2 people working on the same PNG conversion). Provide the screenshot of the PNG image so that we can figure out which PNG you are working on**

----------------------------------

# Important points

1. Please refrain from using tools that convert PNGs to SVGs. **YOU HAVE TO DO THIS MANUALLY.**
   - Please work on this ONLY if you know how/want to learn how to create SVGs
2. **We accept 1 PNG conversion per PR.** 
   - **Example**: checkout `footstep2.svg` in this PR: #134
4. Original PNG can be found in [assets/png](https://github.com/WalkingPal/walking-pal-web/tree/dev/assets/png)

## Current Progress

- [x] WalkingPal logo (@KaranSinghBisht #32 )
- [x] [footstep2.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/footstep2.png) (@annalbirena #134)
- [x] [footstep.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/footstep.png) (@annalbirena #167)
- [x] [pin.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/pin.png) (@senali-d #155 )
- [x] [bagpack.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/bagpack.png) (@spoloxs  #168)
- [ ] [404.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/404.png)
- [ ] [clip.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/clip.png)
- [ ] [credit.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/credit.png)
- [ ] [founders-hub.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/founders-hub.png)
- [ ] [promotion.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/promotion.png)
- [ ] [shape1.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/shape1.png)
- [ ] [shopping.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/shopping.png)

### PR DESCRIPTION
**Pull request by MohamedMetwalli5**
## Proposed Changes
Converted founders-hub.png to founders-hub.svg
- issue #141

### CODE REVIEW

**Comment by MohamedMetwalli5** [comment]
When downloading the svg file it will be shown properly.

**Comment by ashuvssut** [comment]
This contribution is not valid. Kindly read the description in issue #141 

Also, you were not assigned to any issues. Please follow Contributing Guidelines (contributing.md)

**Comment by ashuvssut** [comment]
You may close this PR, if you think you do not want to work on it any further. Thanks

**Comment by ashuvssut** [comment]
These changes are not required for this project

Closing this PR due to inactivity

**Pull request closed without merging**
