### PR TITLE
Accessibility improvements

### LINKED ISSUE #123: bug: need accessibility improvements
### Description

The accessibility of this site can be improved. For example, there is
- the lack of lang attribute in html element
- link icons don't have alt text / title
- headings are not correctly ordered (sequentially-descending order)
- Color contrast issues
- Empty links
- etc etc
- make sure to do these accessibility improvements in **global components** too that are present in the page you are working on (for example `ScrollToTop` button or `Header` component)

Make a draft PR first. Your PR's build will be deployed.
You can use https://wave.webaim.org/report#/<PUT-YOUR-PR's-PREVIEW-BUILD's-URL-HERE> to do all your accessibility analysis. Do analysisi on the latest Preview build only. 

> Checkout the file changes and PR review comments [in this PR](https://github.com/WalkingPal/walking-pal-web/pull/127) to get more clear view on what changes you need to do.

> There are 5 pages. We need to do this in all 5 pages.

----------------------
### Progress

- [x] Home page (@satnaing   )
- [x] About page (@Asmi-1 )
- [x] Company page (@satnaing   )
- [x] FAQs page (@senali-d )
- [ ] Register and 404 page (@senali-d )
--------------------

⚠**Contributors who are interested, please tell beforehand that which page you are going to start working on. This will avoid clashes (possibility of 2 people working on the same page).**

### PR DESCRIPTION
**Pull request by senali-d**
## Proposed Changes

Accessibility improvements
  - Register
  - 404

closes #123

### CODE REVIEW

**Comment by ashuvssut** [comment]
image
These 2 errors are related to each other.

I was not able to fix it in my commit db1b95b 

If you think you can fix it, it would be great!

Rest LGTM! Thanks for your contribution.

**Comment by senali-d** [comment]
Let me check.

**Comment by senali-d** [comment]
@ashuvssut 

- Form label is present but it is not correctly associated with form control.

This issue came along with the MUI. `id` we assign here apply to the top level div of input field. Didn't get any method for apply id to input field.


select

**Comment by ashuvssut** [comment]
Thanks for pointing that out. Issue fixed via 9852523

**Pull request merged**
