### PR TITLE
fix(footer): Fixes issue #45

### PR DESCRIPTION
**Pull request by yunsuklee**
Correcting the footer social icons that were getting in front of the website's logo.

### CODE REVIEW

**Comment by ashuvssut** [comment]
link this PR to its respective issue. Issues must describe your PR properly. use screenshots

kindly refer contributing guidelines. All this has been already mentioned there

**Comment by yunsuklee** [comment]
Screenshot from 2022-10-01 23-46-18
Screenshot from 2022-10-02 11-25-29
Screenshot from 2022-10-02 11-25-44

Hey! Not sure how to link a PR to an existing issue, hope this works.

**Comment by ashuvssut** [comment]
Hey @yunsuklee, we are aware of this issue and this is being already worked on.

refer issue #45 
and see ....^^^^ (this). This is how you link your issue. First create a issue, then put #<issue_id>. same goes for linking PRs. You can [read this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for more details

**Comment by ashuvssut** [comment]
Since this issue is being already worked on, I am closing this PR. Thanks!

**Pull request closed without merging**
